import sqlite3
def create_tables(db):
    conn = sqlite3.connect(db)
    c = conn.cursor()

    c.execute('''CREATE TABLE sites
			(ID INTEGER primary key,
			site_name str,
			code_name str)''')

    c.execute('''CREATE TABLE L2
			(ID INTEGER primary key,
			site_id REFERENCES sites(ID),
			YEAR int,
			GAP int,
			DTIME double,
      DOY int,
			HRMIN int,
			UST double,
			TA double,
			WD double,
			WS double,
			NEE double,
			FC double,
			SFC double,
			H double,
			SH double,
			LE double,
			SLE double,
			FG double,
			TS1 double,
			TSdepth1 double,
			TS2 double,
      TSdepth2 double,
			PREC double,
			RH double,
			PRESS double,
			CO2 double,
			VDP double,
			SWC1 double,
			SWC2 double,
			Rn double,
			PAR double,
			Rg double,
			Rgdif double,
			PARout double,
      RgOut double,
			Rgl double,
			RglOut double,
			H2O double,
			RE double,
			GPP double,
			CO2top double,
			CO2height double,
			APAR double,
			PARdif double,
			APARpct double,
			ZL double)''')

    c.execute('''CREATE TABLE L4_h
      (ID INTEGER primary key,
      site_id REFERENCES sites(ID),
      Year int,
      Month int,
      Day int,
      Hour double,
      DoY double,
      Rg_f double,
      Rg_fqc int,
      Ta_f double,
      Ta_fqc int,
      VPD_f double,
      VPD_fqc int,
      Ts_f double,
      Ts_fqc int,
      Precip double,
      SWC int,
      H_f double,
      H_fqc int,
      LE_f double,
      LE_fqc int,
      gf_NEE_st int,
      gf_NEE_or int,
      Reco_st double,
      Reco_or double,
      NEE_st_fMDS double,
      NEE_st_fMDSqc int,
      GPP_st_MDS double,
      NEE_or_fMDS double,
      NEE_or_fMDSqc int,
      GPP_or_MDS double,
      NEE_st_fANN double,
      NEE_st_fANNqc int,
      GPP_st_ANN double,
      NEE_or_fANN double,
      NEE_or_fANNqc int,
      GPP_or_ANN double);''')

    conn.commit()
